replicaCount: 1

image: quay.io/telescope/telescope-backend:latest
imagePullPolicy: Always

service:
  name: telescope-backend
  type: ClusterIP
  port: 80
  targetport: 8080

probe:
  readypath: /domains
  livepath: /domains

route:
  name: telescope-backend
  enabled: true
  annotations: {}
  path: /
  hostname: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:   #  cpu: 100m
  #  memory: 128Mi
  # requests:   #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

pullSecret:
  enabled: false
  secretName: "pull-secret"
  secretKey: ".dockerconfigjson"

# Vault values

# Vault storage backend
vaultStorage: "vault-backend"
vaultSecret: "vault-secret"
vaultKey: "token"

# Vault Keys
vault:
  registry2:
    host:
      key: secret/registry2
      property: host
    user:
      key: secret/registry2
      property: user
    password:
      key: secret/registry2
      property: password

postgresql:
  external: false
  init: true
  secretName: postgresql
  host: postgresql
  port: 5432
  username: ""
  password: ""
  adminPassword: ""
  database: "telescope"
  image: registry.redhat.io/rhel9/postgresql-13:latest
