{{- if .Values.postgresql.autogenPassword }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "postgresql.fullname" . }}-autogen
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - {{ include "postgresql.fullname" . }}
  verbs:
  - get
  - list
  - watch
  - update
  - patch
{{- end }}
