{{- if .Values.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    argocd.argoproj.io/hook-delete-policy: HookFailed
stringData:
  databaseName: "{{ .Values.postgresql.database }}"
  databaseUser: "{{ .Values.postgresql.user }}"
  databasePort: "{{ .Values.postgresql.port }}"
{{- if .Values.postgresql.host }}
  databaseHost: "{{ .Values.postgresql.host }}"
{{- else }}
  databaseHost: "{{ include "postgresql.name" . }}"
{{- end }}
{{- if not .Values.postgresql.autogenPassword }}
  {{- ( include "gen.postgresql-password" . ) | indent 2 -}}
{{- end }}
{{- end }}
