apiVersion: v1
kind: Service
metadata:
  name: {{ include "telescope-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "telescope-frontend.fullname" . }}
    chart: {{ template "telescope-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "telescope-frontend.fullname" . }}
    release: {{ .Release.Name }}
