image: quay.io/rhn_gps_cjenkins/telescope-toggle-tabs:latest
imagePullPolicy: Always

service:
  name: telescope-toggle-tabs
  type: ClusterIP
  port: 80
  targetport: 8080

probe:
  readypath: /
  livepath: /

route:
  name: telescope-toggle-tabs
  enabled: true
  annotations: {}
  path: /
  hostname: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:   #  cpu: 100m
  #  memory: 128Mi
  # requests:   #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

pullSecret:
  enabled: false
  secretName: "pull-secret"
  secretKey: ".dockerconfigjson"

postgresql:
  external: false
  secretName: postgresql
  host: postgresql
  port: 5432
  username: ""
  password: ""
  adminPassword: ""
  database: "telescope"
