{{- if .Values.postgresql.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  databaseName: "{{ required "Database Name is required" .Values.postgresql.database }}"
  databaseUser: "{{ required "Database User is required" .Values.postgresql.user }}"
  databasePort: "{{ required "Database Port is required" .Values.postgresql.port }}"
  databaseHost: "{{ required "Database Host is required" .Values.postgresql.host }}"
  databasePassword: "{{ required "Database Password is required" .Values.postgresql.databasePassword }}"
{{- end }}
